# See documentation at http://goreleaser.com
version: 2
builds:
  - main: ./cmd/xc
    id: xc
    binary: xc
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - arm
      - amd64
      - arm64
    goarm:
      - 7
      - 6
    ldflags:
      - -s -w
    gcflags:
      - " -l -l -l"
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm
        goarm: 6
brews:
  -
    ids:
      - brew
    goarm: 7
    repository:
      owner: joerdav
      name: homebrew-xc
    description: Self documenting task runner
    homepage: https://github.com/joerdav/xc
    license: "MIT"
signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
archives:
  - formats: [ 'binary' ]
    id: xc
  - formats: ['tar.gz']
    id: brew
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
